/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.junit.Assert.*;

public class App {
    public String getGreeting() {
        return "Hello world!";
    }
};

